version: '3.6'


networks:
  pg:
    name: pg
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.222.0/24
  t2_proxy:
    external: true
  socket_proxy:
    external: true

services:
  postgres:
    image: docker.io/bitnami/postgresql:13
    container_name: postgres
    #    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/postgres:/postgres
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-998}
      TZ: ${TZ:-America/New_York}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-yaba}
      POSTGRES_USER: ${POSTGRES_USER:-yaba}
      APP_SECRET: ${APP_SECRET}
    restart: always
    logging:
      options:
        max-size: "50m"
    networks:
      pg:
        ipv4_address: 192.168.222.251
    ports:
      - "5435:5432"
    security_opt:
      - no-new-privileges:true
  yaba-server:
    container_name: yabaServerSandbox
    image: ruffcode.azurecr.io/yaba-server:0.1.3-SNAPSHOT
    #    network_mode: host
    networks:
      - t2_proxy
      - pg
      - socket_proxy
    #    depends_on:
    #      - socket-proxy
    ports:
      - "9050:9050"
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: ${TZ}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_BASE_URL: ${PLAID_BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      APP_SECRET: ${APP_SECRET}
    logging:
      options:
        max-size: "50m"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.yaba-sb-rtr.entrypoints=https"
      - "traefik.http.routers.yaba-sb-rtr.rule=Host(`yabasandbox.alexib.dev`)"
      ## Middlewares
      - "traefik.http.routers.yaba-sb-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.yaba-sb-rtr.service=yaba-sb-svc"
      - "traefik.http.services.yaba-sb-svc.loadbalancer.server.port=9050"
      - "traefik.http.services.yaba-sb-svc.loadbalancer.passhostheader=true"
