spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:${db.url}
    username: ${db.username}
    password: ${db.password}
    pool:
      initial-size: 2
      max-size: 25
      max-life-time: 5
  application:
    name: YABA


logging.level:
  org.springframework.r2dbc: debug
  org.springframework.data.r2dbc: debug
  web: debug

db:
  username: ${POSTGRES_USER:yaba}
  password: ${POSTGRES_PASSWORD:yaba}
  url: postgresql://${POSTGRES_HOST:192.168.251.251}:${POSTGRES_PORT:5432}/${POSTGRES_DB:yaba}
server:
  port: ${SERVER_PORT:9050}

plaid:
  client-id: ${PLAID_CLIENT_ID:random}
  secret: ${PLAID_SECRET:random}
  base-url: ${PLAID_BASE_URL:https://sandbox.plaid.com}
  hook-url: ${WEBHOOK_URL:https://ruffrevival.ngrok.io/hook}

app:
  secret: ${APP_SECRET:thisissupersecret}
  refresh: letsrefresh
graphql:
  packages:
    - "tech.alexib.yaba.server"
    - "tech.alexib.yaba.domain"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000
  playground:
    enabled: true

service-account:
  path: sa1.json


---

spring:
  config:
    activate:
      on-profile: prod

service-account:
  path: sa.json

sentry:
  dsn: https://c04f38de27db4a36895fc3dfe4cee212@o921828.ingest.sentry.io/5870106

logging.level:
  org.springframework.r2dbc: warn
  org.springframework.data.r2dbc: warn
  web: error
